### ISSUE TITLE
Unable to style borders or outlines of input boxes with class

### ISSUE THREAD

**Issue by ejoflo** [vikignt/svelte-ui#20]
When attempting to change the color of an input/text field border or outline (using class) in a Svelte component, the color does not change.

Example:
`<style>
.input-border {
  border-color: #fff;
}
</style>`

`<Textfield class="input-border" />`

**Comment by vikignt** [comment]
Play with css variables like so
```css
:global(.input-border) {
	--label: White;
	--color: Yellow;
	--primary: Green;
}
```
