### ISSUE TITLE
datepicker isAllowed function not enforcing

### ISSUE THREAD

**Issue by lsalim19** [vikignt/svelte-ui#28]
When using the Datepicker component, setting up isAllowed function only prevents the hover color, but does not prevent the selection of the date.

**Comment by vikignt** [comment]
Try add a global class for the disabled state, like so

```css
    .disabled,
    [disabled] {
        opacity: 0.5;
        pointer-events: none;
    }
```

it's described in the readme and on the example homepage. Notify me if there are any problems.
